apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: homechef
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: homecheff/auth-service
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-auth-0.postgres:5432/auth_db
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-auth-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-auth-secret
                  key: POSTGRES_PASSWORD
            - name: REDIS_HOST
              value: "redis-auth"  # Kubernetes Service name for Redis
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                    secretKeyRef:
                      name: redis-auth-secret  # Store password in a Secret
                      key: redis.password
            - name: auth-service.url
              value: http://auth-service:8080/