apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: homechef
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: cart-service
          image: homecheff/product-service
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: mongo-product-secret
                  key: URI
            - name: SPRING_DATA_MONGODB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mongo-product-secret
                  key: MONGO_DB_NAME



            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq-service
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_DEFAULT_USER
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_DEFAULT_PASS
#            - name: REDIS_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: redis-cart-secret  # Store password in a Secret
#                  key: redis.password
#            - name: auth-service.url
#              value: http://auth-service:8080/