spring:
  application:
    name: ChatService

  cassandra:
    local-datacenter: datacenter1
    keyspace-name: ${CASSANDRA_KEYSPACE:chat_keyspace}
    contact-points: ${CASSANDRA_HOST:localhost}
    port: ${CASSANDRA_PORT:9042}
    schema-action: create_if_not_exists

server:
  port: 8083
