spring:
  application:
    name: ChatService

  cassandra:
    local-datacenter: datacenter1
    keyspace-name: ${CASSANDRA_KEYSPACE:chat_keyspace}
    contact-points: ${CASSANDRA_HOST:localhost}
    port: ${CASSANDRA_PORT:9042}
    schema-action: create_if_not_exists

seeder:
  batch-size: 50

logging:
    level:
      root: INFO
      com.datastax.driver.core: WARN
      com.datastax.driver.core.QueryLogger: ERROR


server:
  port: 8083


jwt:
  secret: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
  expiration: 85400000


