spring:
    application:
        name: api-gateway
    main:
      web-application-type: reactive

    cloud:
        gateway:
          routes:
            # TODO: change names and routes and stuff as appropriate later on
            - id: authentication-service
              uri: http://localhost:8081/
              predicates:
                - Path=/auth/**
              filters:
                - AuthenticationFilter

            - id: cart-service
              uri: http://localhost:8082/
              predicates:
                - Path=/carts/**
              filters:
                - AuthenticationFilter


            - id: order-service
              uri: http://localhost:8084/
              predicates:
                - Path=/orders/**
              filters:
                - AuthenticationFilter


            - id: chat-service
              uri: http://localhost:8083/
              predicates:
                - Path=/messages/**
              filters:
                - AuthenticationFilter

            - id: product-service
              uri: http://localhost:8085/
              predicates:
                - Path=/products/**
              filters:
                - AuthenticationFilter



server:
  port: 8080

jwt:
  secret: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
  expiration: 86400000 # 24 hours in milliseconds