spring:
  application:
    name: CartService
  data:
    mongodb:
      uri: mongodb://bahy:alansary@localhost:27017/elsolasyelmare7?authSource=admin
      database: elsolasyelmare7
server:
  port: 8082