spring:
  application:
    name: CartService
  data:
    mongodb:
      uri: mongodb://bahy:alansary@localhost:27017/elsolasyelmare7?authSource=admin
      database: elsolasyelmare7
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8082
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param