apiVersion: v1
kind: Service
metadata:
  name: mongo-cart
  namespace: homechef
  labels:
    app: mongo-cart
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None  # Headless service
  selector:
    app: mongo-cart