apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cart
  namespace: homechef
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-cart
  template:
    metadata:
      labels:
        app: redis-cart
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
