spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true


  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-email-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  spring:
    redis:
      host: localhost
      port: 6379
      password: redis-password
      timeout: 60000
      database: 0
  otp:
    expiration: 300000 # Expiration time in milliseconds (e.g., 5 minutes)
    token-length: 6     # Number of digits in the OTP
    algorithm: HmacSHA256 # Algorithm for generating OTP (e.g., HmacSHA256)
    max-attempts: 3
    block-duration: 600000

server:
  port: 8081

jwt:
  secret: your-256-bit-secret-key-here
  expiration: 86400000 # 24 hours in milliseconds