# cassandra-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cassandra
  namespace: homechef
spec:
  selector:
    app: cassandra
  ports:
    - port: 9042
      targetPort: 9042
  clusterIP: None  # Headless service for direct pod DNS resolution