apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
  namespace: homechef
  labels:
    app: cassandra
spec:
  serviceName: cassandra  # Required for StatefulSet
  replicas: 1  # Recommended minimum for Cassandra
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
#      terminationGracePeriodSeconds: 1800  # Important for graceful shutdown
      containers:
        - name: cassandra
          image: cassandra:4.0
          ports:
            - containerPort: 7000  # Internode communication
            - containerPort: 7001  # TLS internode
            - containerPort: 9042  # CQL
            - containerPort: 9160  # Thrift
          env:
            - name: CASSANDRA_DC
              value: "datacenter1"
            - name: CASSANDRA_CLUSTER_NAME
              value: "ChatCluster"
            - name: CASSANDRA_NUM_TOKENS
              value: "256"
            - name: CASSANDRA_ENDPOINT_SNITCH
              value: GossipingPropertyFileSnitch
            - name: CASSANDRA_SEEDS
              value: "cassandra"  # First pod as seed (big)
            - name: CASSANDRA_KEYSPACE
              valueFrom:
                secretKeyRef:
                  name: cassandra-secret
                  key: CASSANDRA_KEYSPACE
          volumeMounts:
            - name: cassandra-data
              mountPath: /var/lib/cassandra
          livenessProbe:
            exec:
              command: [ "cqlsh", "-e", "DESCRIBE KEYSPACES" ]
            initialDelaySeconds: 120  # Wait longer for Cassandra to start (60 → 120)
            timeoutSeconds: 5         # Increase timeout (default: 1s → 5s)
            periodSeconds: 20
            failureThreshold: 3       # Allow more retries
  volumeClaimTemplates:
    - metadata:
        name: cassandra-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi  # Adjust size as needed