services:
  cassandra:
    image: cassandra:4.0
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_DC: "datacenter1"
      CASSANDRA_CLUSTER_NAME: "ChatCluster"
      CASSANDRA_NUM_TOKENS: "256"
      CASSANDRA_KEYSPACE: "chat_keyspace"


  chatservice:
    container_name: chatservice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      CASSANDRA_HOST: cassandra
      CASSANDRA_PORT: 9042
      CASSANDRA_KEYSPACE: chat_keyspace
    depends_on:
      - cassandra