services:
  cassandra:
    image: cassandra:4.0
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_DC: "datacenter1"
      CASSANDRA_CLUSTER_NAME: "ChatCluster"
      CASSANDRA_NUM_TOKENS: "256"
      CASSANDRA_KEYSPACE: "chat_keyspace"
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 20s
      timeout: 5s
      retries: 5


  chatservice:
    container_name: chatservice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - CASSANDRA_HOST=cassandra
    depends_on:
      cassandra:
        condition: service_healthy