services:
  api_gateways:
    build:
      context: ./API-Gateway
      dockerfile: Dockerfile
    environment:
      spring.datasource.url: jdbc:postgresql://host.docker.internal:5432/auth_db
      spring.datasource.username: postgres
      spring.datasource.password: 1234
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
    restart: always
  auth_service:
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    environment:
      spring.datasource.url: jdbc:postgresql://host.docker.internal:5432/auth_db
      spring.datasource.username: postgres
      spring.datasource.password: 1234
      spring.data.redis.host: redis_cache
      spring.data.redis.port: 6379
    ports:
      - "8081:8081"
    depends_on:
      - postgres_db
      - redis_cache
    restart: always
  postgres_db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
  redis_cache:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
  redis_insight:
    image: redis/redisinsight:latest
    container_name: redis_insight
    ports:
      - "5540:5540"
    depends_on:
      - redis_cache
    restart: always