services:
  apiGateways:
    build:
      context: ./API-Gateway
      dockerfile: Dockerfile
    environment:
      spring.datasource.url: jdbc:postgresql://host.docker.internal:5432/auth_db
      spring.datasource.username: postgres
      spring.datasource.password: 1234
    ports:
      - "8080:8080"
    depends_on:
      - postgresDB
    restart: always
  authService:
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    environment:
      spring.datasource.url: jdbc:postgresql://host.docker.internal:5432/auth_db
      spring.datasource.username: postgres
      spring.datasource.password: 1234
    ports:
      - "8081:8081"
    depends_on:
      - postgresDB
    restart: always
  postgresDB:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"