apiVersion: v1
kind: Secret
metadata:
  name: postgres-auth-secret
  namespace: homechef
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=       # base64 for "postgres"
  POSTGRES_PASSWORD: MTIzNA==  # base64 for "1234"
  POSTGRES_DB: YXV0aF9kYg==   # base64 for "auth_db"