apiVersion: v1
kind: Secret
metadata:
  name: postgres-order-secret
  namespace: homechef
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=       # base64 for "postgres"
  POSTGRES_PASSWORD: cGFzcw==  # base64 for "pass"
  POSTGRES_DB: T3JkZXJTZXJ2aWNl   # base64 for "OrderService"